# Generated by Django 3.2.14 on 2022-12-06 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atendimentos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('cnpj', 'Pessoa Jurídica'), ('cpf', 'Pessoa Física')], max_length=4, verbose_name='Tipo de Pessoa')),
                ('nome', models.CharField(max_length=250, verbose_name='Nome')),
                ('slug', models.SlugField(max_length=250, verbose_name='Slug')),
                ('identificador', models.CharField(max_length=20, unique=True, verbose_name='CNPJ/CPF')),
                ('endereco', models.CharField(max_length=50, verbose_name='Endereço')),
                ('telefone', models.CharField(max_length=50, verbose_name='Telefone')),
            ],
            options={
                'verbose_name': 'Cliente',
                'verbose_name_plural': 'Clientes',
                'ordering': ['nome'],
            },
        ),
    ]
