# Generated by Django 3.2.14 on 2022-12-06 08:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('atendimentos', '0004_categoria_servico'),
    ]

    operations = [
        migrations.CreateModel(
            name='Departamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('local', models.CharField(max_length=150, verbose_name='Local')),
                ('slug', models.SlugField(max_length=150, verbose_name='Slug')),
                ('descricao', models.TextField(max_length=500, verbose_name='Descrição')),
                ('cliente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='departamento_cliente', to='atendimentos.cliente')),
            ],
            options={
                'verbose_name': 'Departamento',
                'verbose_name_plural': 'Departamentos',
                'ordering': ['local'],
            },
        ),
    ]
