# Generated by Django 3.2.14 on 2022-12-06 08:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('atendimentos', '0005_departamento'),
    ]

    operations = [
        migrations.CreateModel(
            name='Solicitacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('situacao', models.CharField(blank=True, choices=[('pendente', 'Pedente'), ('aguardando_peca', 'Aguardando Peça'), ('andamento', 'Em andamento'), ('finalizado', 'Finalizado')], max_length=20, verbose_name='Situação')),
                ('data_abertura', models.DateTimeField(verbose_name='Data de Abertura')),
                ('data_fechamento', models.DateTimeField(verbose_name='Data de Fechamento')),
                ('prioridade', models.CharField(choices=[('alta', 'Alta'), ('media', 'Média'), ('baixa', 'Baixa')], max_length=20, verbose_name='Prioridade')),
                ('desc_problema', models.TextField(verbose_name='Descrição do Problema')),
                ('desc_resolucao', models.TextField(verbose_name='Resolução')),
                ('slug', models.SlugField(max_length=250, verbose_name='Slug')),
                ('categoria', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='solicitacao_categoria', to='atendimentos.categoria_servico')),
                ('cliente', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='solicitacao_cliente', to='atendimentos.cliente')),
                ('departamento', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='solicitacao_departamento', to='atendimentos.departamento')),
                ('empresa', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='solicitacao_empresa', to='atendimentos.empresa')),
                ('tecnico', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='solicitacao_tecnico', to='atendimentos.cliente')),
            ],
            options={
                'verbose_name': 'Solicitação',
                'verbose_name_plural': 'Solitaçãoes',
                'ordering': ['data_abertura'],
            },
        ),
    ]
