# Generated by Django 3.2.14 on 2022-12-06 09:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('atendimentos', '0006_solicitacao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solicitacao',
            name='cliente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='solicitacao_cliente', to='atendimentos.cliente'),
        ),
    ]
