# Generated by Django 3.2.14 on 2022-12-06 23:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atendimentos', '0007_alter_solicitacao_cliente'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solicitacao',
            name='situacao',
            field=models.CharField(blank=True, choices=[('pendente', 'Pedente'), ('aguardando_peca', 'Aguardando Peça'), ('andamento', 'Em andamento'), ('finalizado', 'Finalizado')], max_length=20, null=True, verbose_name='Situação'),
        ),
    ]
