# Generated by Django 3.2.14 on 2022-12-07 00:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atendimentos', '0009_auto_20221206_2007'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tipo_atendimento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=250, verbose_name='Nome')),
            ],
            options={
                'verbose_name': 'Tipo de Atendimento',
                'verbose_name_plural': 'Tipo de Atendimentos',
                'ordering': ['nome'],
            },
        ),
    ]
