# Generated by Django 3.2.14 on 2022-12-07 00:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atendimentos', '0010_tipo_atendimento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tipo_atendimento',
            name='nome',
            field=models.CharField(max_length=250, verbose_name='nome'),
        ),
    ]
