# Generated by Django 3.2.14 on 2022-12-07 01:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atendimentos', '0011_alter_tipo_atendimento_nome'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tipo_departamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=250, verbose_name='nome')),
            ],
            options={
                'verbose_name': 'Tipo de Departamentos',
                'verbose_name_plural': 'Tipo de Departamentos',
                'ordering': ['nome'],
            },
        ),
    ]
