# Generated by Django 3.2.14 on 2022-12-07 02:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('atendimentos', '0014_auto_20221206_2159'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ordem_servico',
            options={'ordering': ['tipo_departamento'], 'verbose_name': 'Ordem de Serviço', 'verbose_name_plural': 'Ordem de Serviços'},
        ),
    ]
